### PR TITLE
[Stride] Changes the pin types of `ColorMap`, `ColorIn` (and others) to `GPU<RGBA>`

### PR DESCRIPTION
**Pull request by azeno**
# PR Details

## Description

This PR contains breaking changes as it changes the type on well knows nodes like `ColorMap` and `ColorIn` as well as internal sink nodes like `ComposeDrawShader`.

There are probably even more places where the type should be changed to `GPU<RGBA>`. We should further ensure that conversion nodes from RGBA and Color4 are present. Note that those nodes will be a no-op on GPU side.

## Related Issue

#643 

## Motivation and Context

Once we start add/change shaders to make use of `GPU<RGBA>` pins it's only logical to be able to connect those pins to the obvious candidates such as `ColorMap` or `ColorIn`. Also sink nodes composing a pixel shader should express their intent by using this new pin type. 

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation

### CODE REVIEW

**Comment by joreg** [comment]
- check all current nodes with ComputeFloat4 inputs, like: TextureFX, ShaderFX, Colors on material nodes

**Comment by azeno** [comment]
#652 should be merged first before continuing work on this one.

**Comment by azeno** [comment]
> helppatches of texturefx nodes are not found: eg. press F1 on the Metallica node
> 
fixed
>  many shader related enums are still in main Stride pack under "Advanced" aspect
> 
done
>  some "Experimental" Filters are still in main Stride pack
> 
moved
>  shall we only allow ComputeColor instead of also the [Color] attribute for ComputeFloat4?
> 
done (https://github.com/vvvv/VL.StandardLibs/commit/bdc69139c6bc4cbea321998c4e356c16f976e75d)
> shall we also add a "VectorMap" node that returns GPU(Vector4)? and then SwizzleMap...
> 
no, use new Convert (RGBAToVector4) for that
> SetAlpha has Mask GPU(Vector4) input, see keying help
> 
use new Convert (RGBAToVector4)

**Comment by joreg** [comment]
- [ ] SetAlpha node does not show up as "Also found in HowTo Key a Texture" help

**Pull request merged**
